processors:
  - stylelint-processor-styled-components

extends:
  - stylelint-config-standard
  - stylelint-config-styled-components

syntax: scss

rules:
  # TODO: This messes with prettier, there should be a better way to integrate the tools
  declaration-colon-newline-after: null
