# Permalinks
permalink: none

# Setup
title: Jia Hao
tagline: My Blog
description:         Hello!
url:                 https://www.jiahaog.com
paginate:            5
baseurl:             ""

# Assets
sass:
  style: :compressed

author:
  name: Jia Hao Goh
  url: https://twitter.com/jiahaog
  email:

future: true

responsive_image:
  template: _includes/responsive-image.html

  output_path_format: assets/img/resized/%{filename}-%{width}x%{height}.%{extension}
  save_to_source: false

  sizes:
    - width: 240
    - width: 480
    # - width: 640
    # - width: 1280
    # - width: 1920
    # - width: 2560

collections:
  albums:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
