# Permalinks
permalink: pretty

# Setup
title: Jia Hao
tagline: My Blog
description:         Hello!
url:                 http://jiahaog.com
paginate:            5
baseurl:             ""

# Assets
sass:
  style: :compressed

# About/contact
author:
  name: Jia Hao Goh
  url: https://twitter.com/jiahaog
  email:

# Custom vars
version: 2.1.0
github:
  repo: https://github.com/jiahaog/jiahaog.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
