# Permalinks
permalink: pretty

# Setup
title: Jia Hao
tagline: My Blog
description:         Hello!
url:                 http://jiahaog.com
paginate:            5
baseurl:             ""

# Assets
sass:
  style: :compressed

# About/contact
author:
  name: Jia Hao Goh
  url: https://twitter.com/jiahaog
  email:

plugins:
  - jekyll-paginate
  - kramdown

future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
